// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9VOi9t4j1PkokNjybM0psf3xl7AFSVM0',
    appId: '1:394130180954:web:83144d70b4feaa525a0163',
    messagingSenderId: '394130180954',
    projectId: 'fantastic-d5d00',
    authDomain: 'fantastic-d5d00.firebaseapp.com',
    storageBucket: 'fantastic-d5d00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDNvQ199d8-uDR8pXZlBNmBYvHlJR0N4',
    appId: '1:394130180954:android:ca63a61b991abef95a0163',
    messagingSenderId: '394130180954',
    projectId: 'fantastic-d5d00',
    storageBucket: 'fantastic-d5d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNfTgZ5TpV-FuDkB6lFy7ZAHu84sTbao',
    appId: '1:394130180954:ios:01f532ce942e0fb85a0163',
    messagingSenderId: '394130180954',
    projectId: 'fantastic-d5d00',
    storageBucket: 'fantastic-d5d00.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNfTgZ5TpV-FuDkB6lFy7ZAHu84sTbao',
    appId: '1:394130180954:ios:01f532ce942e0fb85a0163',
    messagingSenderId: '394130180954',
    projectId: 'fantastic-d5d00',
    storageBucket: 'fantastic-d5d00.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9VOi9t4j1PkokNjybM0psf3xl7AFSVM0',
    appId: '1:394130180954:web:238b84173f21c9285a0163',
    messagingSenderId: '394130180954',
    projectId: 'fantastic-d5d00',
    authDomain: 'fantastic-d5d00.firebaseapp.com',
    storageBucket: 'fantastic-d5d00.appspot.com',
  );
}
